[2024-09-13T00:52:28.693-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T00:52:28.699-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.task_elt_documento_pagar manual__2024-09-13T03:52:24.767163+00:00 [queued]>
[2024-09-13T00:52:28.703-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.task_elt_documento_pagar manual__2024-09-13T03:52:24.767163+00:00 [queued]>
[2024-09-13T00:52:28.703-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T00:52:28.817-0300] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): task_elt_documento_pagar> on 2024-09-13 03:52:24.767163+00:00
[2024-09-13T00:52:28.820-0300] {standard_task_runner.py:72} INFO - Started process 44802 to run task
[2024-09-13T00:52:28.822-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'task_elt_documento_pagar', 'manual__2024-09-13T03:52:24.767163+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpkuu998qt']
[2024-09-13T00:52:28.823-0300] {standard_task_runner.py:105} INFO - Job 64: Subtask task_elt_documento_pagar
[2024-09-13T00:52:28.848-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.task_elt_documento_pagar manual__2024-09-13T03:52:24.767163+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-13T00:52:28.896-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='task_elt_documento_pagar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T03:52:24.767163+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T03:52:24.767163+00:00'
[2024-09-13T00:52:28.897-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T00:52:28.909-0300] {base.py:84} INFO - Retrieving connection 'spark'
[2024-09-13T00:52:28.910-0300] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 30g --name arrow-spark --deploy-mode client ./dags/sparkjob.py
[2024-09-13T00:52:30.253-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:30 WARN Utils: Your hostname, DESKTOP-PEJJLJO resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2024-09-13T00:52:30.255-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:30 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-09-13T00:52:31.135-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkContext: Running Spark version 3.5.2
[2024-09-13T00:52:31.135-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-13T00:52:31.135-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkContext: Java version 11.0.24
[2024-09-13T00:52:31.192-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-13T00:52:31.267-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceUtils: ==============================================================
[2024-09-13T00:52:31.267-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-13T00:52:31.267-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceUtils: ==============================================================
[2024-09-13T00:52:31.267-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkContext: Submitted application: arrow-spark
[2024-09-13T00:52:31.287-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 30720, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-13T00:52:31.297-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceProfile: Limiting resource is cpu
[2024-09-13T00:52:31.298-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-13T00:52:31.338-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SecurityManager: Changing view acls to: gabzarp
[2024-09-13T00:52:31.339-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SecurityManager: Changing modify acls to: gabzarp
[2024-09-13T00:52:31.339-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SecurityManager: Changing view acls groups to:
[2024-09-13T00:52:31.340-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SecurityManager: Changing modify acls groups to:
[2024-09-13T00:52:31.340-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: gabzarp; groups with view permissions: EMPTY; users with modify permissions: gabzarp; groups with modify permissions: EMPTY
[2024-09-13T00:52:31.559-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO Utils: Successfully started service 'sparkDriver' on port 45567.
[2024-09-13T00:52:31.591-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkEnv: Registering MapOutputTracker
[2024-09-13T00:52:31.623-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-13T00:52:31.637-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-13T00:52:31.638-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-13T00:52:31.642-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-13T00:52:31.677-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b6e33550-d7c4-4c47-80e7-6d63c9cac40b
[2024-09-13T00:52:31.688-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-13T00:52:31.702-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-13T00:52:31.844-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-13T00:52:31.893-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-09-13T00:52:31.903-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:31 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2024-09-13T00:52:32.003-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:32 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:32 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-09-13T00:52:32.046-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /127.0.0.1:7077
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7077
[2024-09-13T00:52:32.047-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-13T00:52:32.048-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:52:52.004-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:52 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - 24/09/13 00:52:52 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-09-13T00:52:52.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /127.0.0.1:7077
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7077
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-09-13T00:52:52.012-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-13T00:52:52.013-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:53:12.005-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:12 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
[2024-09-13T00:53:12.010-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:12 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
[2024-09-13T00:53:12.010-0300] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - Caused by: java.io.IOException: Failed to connect to /127.0.0.1:7077
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-09-13T00:53:12.011-0300] {spark_submit.py:579} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - ... 4 more
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7077
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-09-13T00:53:12.012-0300] {spark_submit.py:579} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-09-13T00:53:12.013-0300] {spark_submit.py:579} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-09-13T00:53:12.013-0300] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-09-13T00:53:32.005-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-09-13T00:53:32.006-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-09-13T00:53:32.014-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37771.
[2024-09-13T00:53:32.015-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO NettyBlockTransferService: Server created on 10.255.255.254:37771
[2024-09-13T00:53:32.016-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-13T00:53:32.021-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.255.255.254, 37771, None)
[2024-09-13T00:53:32.024-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO BlockManagerMasterEndpoint: Registering block manager 10.255.255.254:37771 with 434.4 MiB RAM, BlockManagerId(driver, 10.255.255.254, 37771, None)
[2024-09-13T00:53:32.026-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.255.255.254, 37771, None)
[2024-09-13T00:53:32.027-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.255.255.254, 37771, None)
[2024-09-13T00:53:32.198-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-09-13T00:53:32.374-0300] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-13T00:53:32.375-0300] {spark_submit.py:579} INFO - File "/home/gabzarp/airflow/dags/sparkjob.py", line 9, in <module>
[2024-09-13T00:53:32.375-0300] {spark_submit.py:579} INFO - inicio = pendulum.datetime.now()
[2024-09-13T00:53:32.375-0300] {spark_submit.py:579} INFO - AttributeError: 'function' object has no attribute 'now'
[2024-09-13T00:53:32.438-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-09-13T00:53:32.452-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO SparkUI: Stopped Spark web UI at http://10.255.255.254:4041
[2024-09-13T00:53:32.454-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO DiskBlockManager: Shutdown hook called
[2024-09-13T00:53:32.458-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-09-13T00:53:32.460-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO ShutdownHookManager: Shutdown hook called
[2024-09-13T00:53:32.461-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-ff2ddf81-fbd4-4b37-a7f7-3698ebbbfaf9
[2024-09-13T00:53:32.463-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-09-13T00:53:32.464-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa1f4e89-39eb-4255-bb0e-8357d2ff1e8c
[2024-09-13T00:53:32.468-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa1f4e89-39eb-4255-bb0e-8357d2ff1e8c/pyspark-838c4471-4219-4cda-8d9d-55d01a4feca6
[2024-09-13T00:53:32.469-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-09-13T00:53:32.471-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa1f4e89-39eb-4255-bb0e-8357d2ff1e8c/userFiles-c1af69a2-83d6-48f8-b4a8-ff230847f764
[2024-09-13T00:53:32.490-0300] {spark_submit.py:579} INFO - 24/09/13 00:53:32 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-09-13T00:53:32.830-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 30g --name arrow-spark --deploy-mode client ./dags/sparkjob.py. Error code is: 1.
[2024-09-13T00:53:32.832-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=task_elt_documento_pagar, run_id=manual__2024-09-13T03:52:24.767163+00:00, execution_date=20240913T035224, start_date=20240913T035228, end_date=20240913T035332
[2024-09-13T00:53:32.842-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T00:53:32.842-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task task_elt_documento_pagar (Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 30g --name arrow-spark --deploy-mode client ./dags/sparkjob.py. Error code is: 1.; 44802)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 30g --name arrow-spark --deploy-mode client ./dags/sparkjob.py. Error code is: 1.
[2024-09-13T00:53:32.882-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-13T00:53:32.893-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T00:53:33.009-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
