[2024-09-12T13:14:28.025-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T13:14:28.032-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T16:14:24.620108+00:00 [queued]>
[2024-09-12T13:14:28.037-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T16:14:24.620108+00:00 [queued]>
[2024-09-12T13:14:28.037-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T13:14:28.049-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-12 16:14:24.620108+00:00
[2024-09-12T13:14:28.051-0300] {standard_task_runner.py:72} INFO - Started process 19200 to run task
[2024-09-12T13:14:28.053-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-12T16:14:24.620108+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmps2ct5zry']
[2024-09-12T13:14:28.054-0300] {standard_task_runner.py:105} INFO - Job 47: Subtask get_data_from_gs
[2024-09-12T13:14:28.077-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T16:14:24.620108+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T13:14:28.126-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T16:14:24.620108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T16:14:24.620108+00:00'
[2024-09-12T13:14:28.126-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T13:14:28.149-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T13:14:28.150-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T13:14:29.085-0300] {python.py:240} INFO - Done. Returned value was: [['to update', 'fasdf', 'zxvc'], ['asdf', 'xcv', 'as'], ['Swf', 'zxcv', 'fd']]
[2024-09-12T13:14:29.099-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T13:14:29.099-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-12T16:14:24.620108+00:00, execution_date=20240912T161424, start_date=20240912T161428, end_date=20240912T161429
[2024-09-12T13:14:29.149-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T13:14:29.161-0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-12T13:14:29.166-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
