[2024-09-13T01:43:55.127-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T01:43:55.135-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-13T04:43:35.957396+00:00 [queued]>
[2024-09-13T01:43:55.139-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-13T04:43:35.957396+00:00 [queued]>
[2024-09-13T01:43:55.139-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T01:43:55.151-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_data> on 2024-09-13 04:43:35.957396+00:00
[2024-09-13T01:43:55.155-0300] {standard_task_runner.py:72} INFO - Started process 86039 to run task
[2024-09-13T01:43:55.158-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'update_data', 'manual__2024-09-13T04:43:35.957396+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpavb70mwc']
[2024-09-13T01:43:55.159-0300] {standard_task_runner.py:105} INFO - Job 80: Subtask update_data
[2024-09-13T01:43:55.188-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.update_data manual__2024-09-13T04:43:35.957396+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-13T01:43:55.235-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='update_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T04:43:35.957396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T04:43:35.957396+00:00'
[2024-09-13T01:43:55.235-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T01:43:55.247-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-13T01:43:55.248-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-13T01:43:56.682-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T01:43:56.687-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T01:43:56.688-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=update_data, run_id=manual__2024-09-13T04:43:35.957396+00:00, execution_date=20240913T044335, start_date=20240913T044355, end_date=20240913T044356
[2024-09-13T01:43:56.736-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T01:43:56.748-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T01:43:56.748-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
