[2024-09-12T03:53:30.944-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T03:53:30.950-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:53:28.497850+00:00 [queued]>
[2024-09-12T03:53:30.954-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:53:28.497850+00:00 [queued]>
[2024-09-12T03:53:30.954-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T03:53:30.965-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-12 06:53:28.497850+00:00
[2024-09-12T03:53:30.967-0300] {standard_task_runner.py:72} INFO - Started process 69931 to run task
[2024-09-12T03:53:30.969-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-12T06:53:28.497850+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpm5adf_ec']
[2024-09-12T03:53:30.970-0300] {standard_task_runner.py:105} INFO - Job 20: Subtask get_data_from_gs
[2024-09-12T03:53:30.991-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:53:28.497850+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T03:53:31.033-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T06:53:28.497850+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T06:53:28.497850+00:00'
[2024-09-12T03:53:31.034-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T03:53:31.045-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T03:53:31.046-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T03:53:31.918-0300] {logging_mixin.py:190} INFO - [['Nome', 'valor', 'sku'], ['produto', '31535', 'fsoi3098312'], ['produto', '147', 'fsoi3098313'], ['produto', '713', 'fsoi3098314'], ['produto', '174', 'fsoi3098315']]
[2024-09-12T03:53:31.918-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T03:53:31.921-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T03:53:31.921-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-12T06:53:28.497850+00:00, execution_date=20240912T065328, start_date=20240912T065330, end_date=20240912T065331
[2024-09-12T03:53:31.944-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T03:53:31.951-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T03:53:31.952-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
