[2024-09-12T12:57:41.302-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T12:57:41.309-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T15:57:35.291800+00:00 [queued]>
[2024-09-12T12:57:41.313-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T15:57:35.291800+00:00 [queued]>
[2024-09-12T12:57:41.313-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T12:57:41.324-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-12 15:57:35.291800+00:00
[2024-09-12T12:57:41.327-0300] {standard_task_runner.py:72} INFO - Started process 9596 to run task
[2024-09-12T12:57:41.329-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-12T15:57:35.291800+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp0tv42us4']
[2024-09-12T12:57:41.330-0300] {standard_task_runner.py:105} INFO - Job 38: Subtask get_data_from_gs
[2024-09-12T12:57:41.353-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T15:57:35.291800+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T12:57:41.401-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T15:57:35.291800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T15:57:35.291800+00:00'
[2024-09-12T12:57:41.402-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T12:57:41.412-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T12:57:41.414-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T12:57:42.433-0300] {dag_test.py:69} INFO - [['teste', 'teste2', 'teste3'], ['produto', '31535', 'fsoi3098312'], ['produto', '147', 'fsoi3098313'], ['produto', '713', 'fsoi3098314'], ['produto', '174', 'fsoi3098315'], ['produto', '123', 'fsoi3098316'], ['produto', '423', 'fsoi3098317'], ['produto', '1234', 'fsoi3098318'], ['produto', '2234', 'fsoi3098319'], ['produto', '546', 'fsoi3098320'], ['produto', '143', 'fsoi3098321'], ['produto', '435', 'fsoi3098322'], ['produto', '6342', 'fsoi3098323']]
[2024-09-12T12:57:42.434-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T12:57:42.437-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T12:57:42.437-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-12T15:57:35.291800+00:00, execution_date=20240912T155735, start_date=20240912T155741, end_date=20240912T155742
[2024-09-12T12:57:42.466-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T12:57:42.474-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T12:57:42.475-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
