[2024-09-12T03:46:35.519-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T03:46:35.524-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:46:33.548136+00:00 [queued]>
[2024-09-12T03:46:35.527-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:46:33.548136+00:00 [queued]>
[2024-09-12T03:46:35.528-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T03:46:35.539-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-12 06:46:33.548136+00:00
[2024-09-12T03:46:35.541-0300] {standard_task_runner.py:72} INFO - Started process 65858 to run task
[2024-09-12T03:46:35.543-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-12T06:46:33.548136+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp55ftx35o']
[2024-09-12T03:46:35.544-0300] {standard_task_runner.py:105} INFO - Job 19: Subtask get_data_from_gs
[2024-09-12T03:46:35.568-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T06:46:33.548136+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T03:46:35.612-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T06:46:33.548136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T06:46:33.548136+00:00'
[2024-09-12T03:46:35.613-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T03:46:35.630-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T03:46:35.631-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T03:46:35.631-0300] {sheets.py:411} INFO - Creating spreadsheet: Test1
[2024-09-12T03:46:37.285-0300] {sheets.py:416} INFO - Spreadsheet: Test1 created
[2024-09-12T03:46:37.285-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T03:46:37.288-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T03:46:37.288-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-12T06:46:33.548136+00:00, execution_date=20240912T064633, start_date=20240912T064635, end_date=20240912T064637
[2024-09-12T03:46:37.321-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T03:46:37.329-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T03:46:37.329-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
