[2024-09-13T01:43:51.724-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T01:43:51.733-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-13T04:43:35.957396+00:00 [queued]>
[2024-09-13T01:43:51.739-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-13T04:43:35.957396+00:00 [queued]>
[2024-09-13T01:43:51.739-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T01:43:51.753-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-13 04:43:35.957396+00:00
[2024-09-13T01:43:51.756-0300] {standard_task_runner.py:72} INFO - Started process 85974 to run task
[2024-09-13T01:43:51.759-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-13T04:43:35.957396+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpum7em37d']
[2024-09-13T01:43:51.761-0300] {standard_task_runner.py:105} INFO - Job 79: Subtask get_data_from_gs
[2024-09-13T01:43:51.791-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-13T04:43:35.957396+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-13T01:43:51.840-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T04:43:35.957396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T04:43:35.957396+00:00'
[2024-09-13T01:43:51.841-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T01:43:51.853-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-13T01:43:51.854-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-13T01:43:52.977-0300] {python.py:240} INFO - Done. Returned value was: [['to update', 'fasdf', 'zxvc'], ['asdf', 'xcv', 'as'], ['Swf', 'zxcv', 'fd']]
[2024-09-13T01:43:52.997-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T01:43:52.997-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-13T04:43:35.957396+00:00, execution_date=20240913T044335, start_date=20240913T044351, end_date=20240913T044352
[2024-09-13T01:43:53.056-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T01:43:53.074-0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-13T01:43:53.081-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
